### ISSUE TITLE
Is there any special consideration here

### ISSUE THREAD

**Issue by 4ever9** [cosmosregistry/chain-minimal#101]
There are 2 duplicate codes there.

https://github.com/cosmosregistry/chain-minimal/blob/ec48ad98bad5e67a6eb4de84ee2424050fcd0995/cmd/minid/cmd/root.go#L91-L99

**Comment by julienrbrt** [comment]
Nope, that is a mistake. Thanks for pointing it out!

**Comment by julienrbrt** [comment]
Fixed by 9bc1a71d69b8414d600421a2f2c2774b646eef7b
