### ISSUE TITLE
ERROR: failed to get genesis app state from config

### ISSUE THREAD

**Issue by amancooks08** [cosmosregistry/chain-minimal#131]
I have modified my `init.sh` file, to give me 2 accounts and a validator, but still while running the `make init` command I am facing, the same error again and again, I've tried using the command directly in the terminal, still it is not working.

Error: `failed to get genesis app state from config: open /Users/user1/.minid/config/gentx: no such file or directory [cosmos/cosmos-sdk@v0.50.5/x/genutil/client/cli/collect.go:56]`

init.sh ::

```
#!/bin/bash

rm -r ~/.minid || true
MINID_BIN=$(which minid)
# configure minid
$MINID_BIN config set client chain-id demo
$MINID_BIN config set client keyring-backend test
$MINID_BIN keys add alice
$MINID_BIN keys add bob
$MINID_BIN keys add validator --keyring-backend test
$MINID_BIN init test --chain-id demo --default-denom mini
# update genesis
$MINID_BIN genesis add-genesis-account alice 10000000mini --keyring-backend test
$MINID_BIN genesis add-genesis-account bob 1000mini --keyring-backend test
$MINID_BIN genesis add-genesis-account validator 1000000000mini --keyring-backend test
# create default validator
$MINID_BIN genesis gentx validator 1000000000mini --chain-id demo --keyring-backend test
$MINID_BIN genesis collect-gentxs
```

**Comment by julienrbrt** [comment]
Hi!

Does it work with the original script?

**Comment by amancooks08** [comment]
Yeah, I tried running it again, but at the end I recloned it a couple of times, and it worked fine, there was a problem with the `genutils` module not being initialized, but it worked like a charm afterwards!
Thanks for reaching out!

**Comment by julienrbrt** [comment]
Awesome!
