### ISSUE TITLE
What steps to follow for changing the chain id?

### ISSUE THREAD

**Issue by ahmadSaeedGoda** [cosmosregistry/chain-minimal#138]
Please consider it a live mainnet, what steps/tutorials/instructions can be followed to achieve this?

I have a network up & running whose ID is conflicting with another live network which causes issues with wallets like MetaMask, and also affects Token symbol being suspicious due to duplicate chain id, which affects the deployed dApps in turn.

Please advise!

Thanks,

**Comment by julienrbrt** [comment]
Hi,

Thank your this issue. As you have opened the same issue in the SDK repo (https://github.com/cosmos/cosmos-sdk/issues/20456). Let's continue the discussion there.

**Comment by ahmadSaeedGoda** [comment]
Awesome,
Thanks to you for the great work you undertake!

Kindly just point out how to continue the discussion here!
Just getting confused as the issue is closed.
