### ISSUE TITLE
Need to be able to run multi local nodes for testing purposes 

### ISSUE THREAD

**Issue by ahmadSaeedGoda** [cosmosregistry/chain-minimal#139]
Having a command to craft a testnet locally can be very helpful to be introduced as a feature.

Thanks in advance,

**Comment by julienrbrt** [comment]
This makes sense, you can look directly at simapp (https://github.com/cosmos/cosmos-sdk/blob/v0.50.6/simapp/simd/cmd/testnet.go) which is a more complete chain example or use ignite (https://docs.ignite.com/references/cli#ignite-network) or spawn (https://github.com/rollchains/spawn/blob/c697428dd09bfc8d0f4a42e74d6512c0cc32f391/simapp/cmd/wasmd/testnet.go#L178-L185)
This repo is made to be as simple as possible.
