### ISSUE TITLE
make `init` error

### ISSUE THREAD

**Issue by cocoyoon** [cosmosregistry/chain-minimal#151]
I got error on `make init`

<img width="955" alt="Screenshot 2024-07-20 at 2 11 20 AM" src="https://github.com/user-attachments/assets/b27e6e5b-3186-4d27-83e5-1130710dbcc7">

**Comment by julienrbrt** [comment]
Hi! Are you show me at which location minid is?

`which minid`

**Comment by cocoyoon** [comment]
Result of `which minid`
<img width="973" alt="image" src="https://github.com/user-attachments/assets/14d0d5e2-b30c-41af-9693-f30f7fee02e9">

**Comment by julienrbrt** [comment]
> Result of `which minid`
> 
> <img width="973" alt="image" src="https://github.com/user-attachments/assets/14d0d5e2-b30c-41af-9693-f30f7fee02e9">
> 
> 

Okay, can you run `minid version` and/or `minid start`

**Comment by cocoyoon** [comment]
Suddenly it works.. Anyway thank you for your support :)
